RentersNz/Controllers/LandlordsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentersNz.Areas.Identity.Data;
using RentersNz.Models;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;

namespace RentersNz.Controllers
{
    public class LandlordsController : Controller
    {
        private readonly RentersNzDbContext _context;

        public LandlordsController(RentersNzDbContext context)
        {
            _context = context;
        }

        // GET: Landlords
        [Authorize]
        public async Task<IActionResult> Index(string searchString)
        {
            var landlords = from l in _context.Landlord
                            select l;

            if (!string.IsNullOrEmpty(searchString))
            {
                landlords = landlords.Where(s => s.Name.Contains(searchString) || s.Email.Contains(searchString));
            }

            ViewData["CurrentFilter"] = searchString;

            return View(await landlords.ToListAsync());
        }

        // GET: Landlords/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landlord = await _context.Landlord
                .FirstOrDefaultAsync(m => m.LandlordId == id);
            if (landlord == null)
            {
                return NotFound();
            }

            return View(landlord);
        }

        // GET: Landlords/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Landlords/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LandlordId,Name,Email,PhoneNumber,Address,City,Region,PostalCode,Description")] Landlord landlord)
        {
            if (ModelState.IsValid)
            {
                _context.Add(landlord);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(landlord);
        }

        // GET: Landlords/Edit/5
        [Authorize(Roles = "Administrators , Testers")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landlord = await _context.Landlord.FindAsync(id);
            if (landlord == null)
            {
                return NotFound();
            }
            return View(landlord);
        }

        // POST: Landlords/Edit/5
        [Authorize(Roles = "Administrators , Editors")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LandlordId,Name,Email,PhoneNumber,Address,City,Region,PostalCode,Description")] Landlord landlord)
        {
            if (id != landlord.LandlordId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(landlord);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LandlordExists(landlord.LandlordId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(landlord);
        }

        // GET: Landlords/Delete/5
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landlord = await _context.Landlord
                .FirstOrDefaultAsync(m => m.LandlordId == id);
            if (landlord == null)
            {
                return NotFound();
            }

            return View(landlord);
        }

        // POST: Landlords/Delete/5
        [Authorize(Roles = "Administrators")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var landlord = await _context.Landlord.FindAsync(id);
            if (landlord != null)
            {
                _context.Landlord.Remove(landlord);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LandlordExists(int id)
        {
            return _context.Landlord.Any(e => e.LandlordId == id);
        }
    }
}

RentersNz/Controllers/RentersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentersNz.Areas.Identity.Data;
using RentersNz.Models;
using System.Linq;
using System.Threading.Tasks;

namespace RentersNz.Controllers
{
    public class RentersController : Controller
    {
        private readonly RentersNzDbContext _context;

        public RentersController(RentersNzDbContext context)
        {
            _context = context;
        }

        // GET: Renters
        [Authorize]
        public async Task<IActionResult> Index(string searchString)
        {
            var renters = from r in _context.Renter
                          select r;

            if (!string.IsNullOrEmpty(searchString))
            {
                renters = renters.Where(s => s.RenterName.Contains(searchString));
            }

            ViewData["CurrentFilter"] = searchString;

            return View(await renters.ToListAsync());
        }

        // GET: Renters/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var renter = await _context.Renter
                .FirstOrDefaultAsync(m => m.RenterId == id);
            if (renter == null)
            {
                return NotFound();
            }

            return View(renter);
        }

        // GET: Renters/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Renters/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RenterId,RenterName,RenterDescription,Bedrooms,Bathrooms,AnimalSupport,SquareFootprint,UnitorStandAlone")] Renter renter)
        {
            if (ModelState.IsValid)
            {
                _context.Add(renter);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(renter);
        }

        // GET: Renters/Edit/5
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var renter = await _context.Renter.FindAsync(id);
            if (renter == null)
            {
                return NotFound();
            }
            return View(renter);
        }

        // POST: Renters/Edit/5
        [Authorize(Roles = "Administrators")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RenterId,RenterName,RenterDescription,Bedrooms,Bathrooms,AnimalSupport,SquareFootprint,UnitorStandAlone")] Renter renter)
        {
            if (id != renter.RenterId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(renter);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RenterExists(renter.RenterId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(renter);
        }

        // GET: Renters/Delete/5
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var renter = await _context.Renter
                .FirstOrDefaultAsync(m => m.RenterId == id);
            if (renter == null)
            {
                return NotFound();
            }

            return View(renter);
        }

        // POST: Renters/Delete/5
        [Authorize(Roles = "Administrators")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var renter = await _context.Renter.FindAsync(id);
            if (renter != null)
            {
                _context.Renter.Remove(renter);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RenterExists(int id)
        {
            return _context.Renter.Any(e => e.RenterId == id);
        }
    }
}

RentersNz/Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentersNz.Areas.Identity.Data;
using RentersNz.Models;
using System.Linq;
using System.Threading.Tasks;

namespace RentersNz.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly RentersNzDbContext _context;

        public ReviewsController(RentersNzDbContext context)
        {
            _context = context;
        }

        // GET: Reviews
        [Authorize]
        public async Task<IActionResult> Index(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            var reviews = from r in _context.Review
                          select r;

            if (!string.IsNullOrEmpty(searchString))
            {
                reviews = reviews.Where(r => r.RenterId.ToString().Contains(searchString)
                                            || r.PropertyId.ToString().Contains(searchString));
            }

            return View(await reviews.ToListAsync());
        }

        // GET: Reviews/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Reviews/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reviews/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,RenterId,PropertyId,Rating,ReviewText")] Review review)
        {
            if (ModelState.IsValid)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Reviews/Edit/5
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            return View(review);
        }

        // POST: Reviews/Edit/5
        [Authorize(Roles = "Administrators")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,RenterId,PropertyId,Rating,ReviewText")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Reviews/Delete/5
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [Authorize(Roles = "Administrators")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Review.FindAsync(id);
            if (review != null)
            {
                _context.Review.Remove(review);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
            return _context.Review.Any(e => e.ReviewId == id);
        }
    }
}

RentersNz/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "RentersNz";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentersNz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentersNz.styles.css" asp-append-version="true" />

    <!-- Integrate Google Font - Roboto -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">

    <style>
        body {
            font-family: 'Montserrat', sans-serif;
            font-size: 16px;
            line-height: 1.5;
            color: #333;
            background-color: #f4f4f4;
        }

        h1 {
            font-size: 2.5rem;
            font-weight: bold;
            margin-bottom: 2rem;
            font-family: 'Roboto', sans-serif; /* Apply Roboto font to header title */
            text-transform: uppercase; /* Uppercase text */
            letter-spacing: 2px; /* Add letter spacing */
            color: #333; /* Color for the header title */
        }

        .house-info {
            display: none;
        }

        .house-listing:hover .house-info {
            display: block;
        }

        .house-listing {
            display: inline-block;
            width: 150px;
            margin: 10px;
            text-align: center;
        }

            .house-listing img {
                width: 100%;
                height: auto;
            }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <h1 class="navbar-brand m-0 p-0" asp-area="" asp-controller="Home" asp-action="Index">RentersNz</h1>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown" id="informationDropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="registerDropdown" role="button" aria-expanded="false">
                                ℹ️ Information
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="registerDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Landlords" asp-action="Index">Landlord</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Renters" asp-action="Index">Renter</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Properties" asp-action="Index">Properties</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="leases" asp-action="Index">Leases</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Reviews" asp-action="Index">Reviews</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Privacy" asp-action="Index">Privacy Policy</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RentersNz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        // Show dropdown on hover
        $('#informationDropdown').hover(function () {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
        }, function () {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
        });
    </script>
</body>
</html>